import type { Metadata } from 'next';
import './globals.css';
import AppProvider from '@/context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <AppProvider>
        <body>{children}</body>
      </AppProvider>
    </html>
  );
}
